name: Build & Release APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Write google-services.json
        run: |
          mkdir -p app
          cat <<EOF > app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Create tokens.xml
        run: |
          mkdir -p app/src/main/res/values
          cat <<EOF > app/src/main/res/values/tokens.xml
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
            <string name="firebase_web_client_id">${{ secrets.FIREBASE_WEB_CLIENT_ID }}</string>
            <string name="APCA_API_KEY_ID">${{ secrets.APCA_API_KEY_ID }}</string>
            <string name="APCA_API_SECRET_KEY">${{ secrets.APCA_API_SECRET_KEY }}</string>
          </resources>
          EOF

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*/.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build release APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Find release APK and name
        id: find_apk
        run: |
          APK=$(find app/build/outputs/apk -type f -name '*.apk' | head -n1)
          echo "Found APK at: $APK"
          echo "apk_path=$APK" >> $GITHUB_OUTPUT
          echo "apk_name=$(basename "$APK")" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_apk.outputs.apk_path }}
          asset_name: ${{ steps.find_apk.outputs.apk_name }}
          asset_content_type: application/vnd.android.package-archive
